name: keystone_dart
description: A Keystone engine assembler binding written in Dart using ffi
version: 1.0.0-dev
homepage: https://github.com/Midi12/keystone_dart
repository: https://github.com/Midi12/keystone_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
