name: keystone_dart
description: Keystone assembler binding written in Dart
# version: 1.0.0
# homepage: https://github.com/Midi12/keystone_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
